name: PyLint

on:
  push:
    paths:
      - "**.py"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" , "3.12" , "3.13" ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')

      - name: Commit changes if any fixes were made
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: apply pylint fixes'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: gabrielmaialva33
          commit_user_email: gabrielmaialva33@gmail.com
          commit_author: Maia <gabrielmaialva33@gmail.com>
