name: PyLint
on:
  push:
    paths:
      - "**.py"
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Run Pylint
        run: |
          pylint $(git ls-files '*.py')
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: lint fixes'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: gabrielmaialva33
          commit_user_email: gabrielmaialva33@gmail.com
          commit_author: Maia <gabrielmaialva33@gmail.com>
